# -*- coding: utf-8 -*-
"""network_trace_generator_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vxkDIat9KJbaTsKW2UWEn2ekRqUKZs0f

# Generador de Trazas de Red Genéricas y Análisis Estadístico (v2)

Este notebook permite generar trazas de red genéricas a partir de la actividad de una Red Neuronal Espiking (SNN) entrenada, con topología y mapeo personalizables. Además, proporciona herramientas para el análisis estadístico de la carga y el tráfico de la red.

**Nota:** Si acabas de instalar las librerías, recuerda **reiniciar el entorno de ejecución** (Runtime -> Restart session) antes de continuar.
"""

# 1. Instalación de dependencias (Solo si no están instaladas)
# !pip install snntorch tonic numpy torch torchvision matplotlib seaborn pandas

# 2. Importar librerías
import numpy as np
import torch
import torch.nn as nn
import torchvision
from torch.utils.data import DataLoader
import tonic
import snntorch as snn
from snntorch import surrogate
from snntorch import functional as SF
from snntorch import utils
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# --- Reproducibilidad ---
torch.manual_seed(42)
np.random.seed(42)

print(f"System Check -> NumPy: {np.__version__} | PyTorch: {torch.__version__}")

# Configuración de dispositivo
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
if device.type != 'cuda':
    print("ADVERTENCIA: CUDA no disponible, usando CPU. Intentando forzar detección...")
print(f"Hardware de entrenamiento: {device}")

"""## 3. Carga y Preprocesamiento de Datos (N-MNIST)"""

sensor_size = tonic.datasets.NMNIST.sensor_size
transform = tonic.transforms.Compose([
    tonic.transforms.ToFrame(sensor_size=sensor_size, n_time_bins=30),
    torch.from_numpy,
    torchvision.transforms.RandomRotation([-10, 10])
])

trainset = tonic.datasets.NMNIST(save_to='./data', train=True)
cached_trainset = tonic.DiskCachedDataset(trainset, transform=transform, cache_path='./cache/nmnist/train')

testset = tonic.datasets.NMNIST(save_to='./data', train=False)
cached_testset = tonic.DiskCachedDataset(testset, transform=transform, cache_path='./cache/nmnist/test')

batch_size = 128
trainloader = DataLoader(cached_trainset, batch_size=batch_size, shuffle=True)
testloader = DataLoader(cached_testset, batch_size=batch_size, shuffle=False)

"""## 4. Definición de la Arquitectura CSNN

En snntorch 0.9.4, cuando se usa `init_hidden=True`, la capa devuelve `(spk, mem)`. Sin embargo, si se usa de forma iterativa sin `init_hidden`, devuelve `(spk, mem)`. El error anterior sugiere que se estaban devolviendo más valores de los esperados o que la inicialización interna estaba causando conflictos.

A continuación, se define la red de forma robusta.
"""

spike_grad = surrogate.atan()
beta = 0.5

class CSNN(nn.Module):
    def __init__(self, beta, spike_grad):
        super().__init__()
        self.conv1 = nn.Conv2d(2, 12, 5)
        self.snn1 = snn.Leaky(beta=beta, spike_grad=spike_grad) # Sin init_hidden
        self.pool1 = nn.MaxPool2d(2)

        self.conv2 = nn.Conv2d(12, 32, 5)
        self.snn2 = snn.Leaky(beta=beta, spike_grad=spike_grad) # Sin init_hidden
        self.pool2 = nn.MaxPool2d(2)

        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(32*5*5, 10)
        self.snn3 = snn.Leaky(beta=beta, spike_grad=spike_grad) # Sin init_hidden

    def forward(self, x, mem1, mem2, mem3):
        # Etapa 1
        cur = self.conv1(x)
        spk1, mem1 = self.snn1(cur, mem1) # Pasamos el estado manualmente
        cur = self.pool1(spk1)

        # Etapa 2
        cur = self.conv2(cur)
        spk2, mem2 = self.snn2(cur, mem2) # Pasamos el estado manualmente
        cur = self.pool2(spk2)

        # Clasificador
        cur = self.flatten(cur)
        cur = self.fc1(cur)
        spk_out, mem3 = self.snn3(cur, mem3) # Pasamos el estado manualmente

        return spk_out, spk1, spk2, mem1, mem2, mem3

# Re-instanciar la red
net = CSNN(beta, spike_grad).to(device)

"""## 5. Entrenamiento de la SNN"""

optimizer = torch.optim.Adam(net.parameters(), lr=2e-3, betas=(0.9, 0.999))
loss_fn = SF.ce_rate_loss()

num_epochs = 1 # Reducido para demostración rápida (Mantener en 1)
num_iters = 100 # Entrenar durante 100 iteraciones para obtener pesos realistas y precisosciando Fase de Entrenamiento ---")
for epoch in range(num_epochs):
    for i, (data, targets) in enumerate(iter(trainloader)):
        data = data.float().to(device).transpose(0, 1) # (time, batch, channel, h, w)
        targets = targets.to(device)

        net.train()
        utils.reset(net) # Resetear estados de membrana para el nuevo batch

        mem1 = net.snn1.init_leaky()
        mem2 = net.snn2.init_leaky()
        mem3 = net.snn3.init_leaky()

        spk_rec = []
        for step in range(data.size(0)):
            # El forward ahora recibe y devuelve los estados de membrana
            spk_out, spk1, spk2, mem1, mem2, mem3 = net(data[step], mem1, mem2, mem3)
            spk_rec.append(spk_out)

        spk_rec = torch.stack(spk_rec)

        loss_val = loss_fn(spk_rec, targets)
        optimizer.zero_grad()
        loss_val.backward()
        optimizer.step()

        if i % 20 == 0:
            acc = SF.accuracy_rate(spk_rec, targets)
            print(f"Epoch {epoch}, Iter {i} | Loss: {loss_val.item():.2f} | Acc: {acc * 100:.2f}%")

        if i == num_iters: break

"""## 6. Configuración de Topología y Mapeo de Red Personalizable"""

# Definición de la topología de la red (ejemplo: una red de 16 nodos en malla 4x4)
num_nodes = 16 # Para una malla 4x4
connections = {}
for i in range(num_nodes):
    connections[i] = []
    # Conexiones para una malla 4x4
    if (i + 1) % 4 != 0: connections[i].append(i + 1) # Este
    if i % 4 != 0: connections[i].append(i - 1)     # Oeste
    if i + 4 < num_nodes: connections[i].append(i + 4) # Sur
    if i - 4 >= 0: connections[i].append(i - 4)     # Norte

print("Topología de red (ejemplo de conexiones):")
for node, conns in connections.items():
    print(f"Nodo {node}: {conns}")

# Mapeo de las capas de la SNN a los nodos de la red (Optimizado para malla 4x4)
# Distribuimos las capas por toda la malla para evitar hotspots en las esquinas
snn_layer_to_nodes_mapping = {
    'input': [0, 1], # Entrada distribuida
    'snn1': [2, 3, 4, 5, 6, 7], # Capa 1 distribuida en el centro
    'snn2': [8, 9, 10, 11, 12, 13, 14], # Capa 2 distribuida en el resto
    'output': [15] # Salida en el último nodo
}

print("\nMapeo de capas SNN a nodos de red:")
for layer, nodes in snn_layer_to_nodes_mapping.items():
    print(f"Capa {layer}: {nodes}")

"""## 7. Generación de Trazas de Red Genéricas"""

def generate_generic_trace(net, data_sample, snn_layer_to_nodes_mapping, connections, filename="generic_trace.txt"):
    print("Iniciando generación de traza...")
    net.eval()
    trace_events = []

    # Inicializar estados de membrana
    mem1 = net.snn1.init_leaky()
    mem2 = net.snn2.init_leaky()
    mem3 = net.snn3.init_leaky()

    print(f"Procesando {data_sample.size(0)} pasos de tiempo...")

    with torch.no_grad():
        for step in range(data_sample.size(0)):
            # Llamada a la red
            out_tuple = net(data_sample[step], mem1, mem2, mem3)
            spk_out, spk1, spk2 = out_tuple[0], out_tuple[1], out_tuple[2]
            mem1, mem2, mem3 = out_tuple[3], out_tuple[4], out_tuple[5]

            # 1. Tráfico del Sensor
            input_spikes = (data_sample[step] > 0).nonzero(as_tuple=False)
            if len(input_spikes) > 0:
                src_node = snn_layer_to_nodes_mapping['input'][0]
                for dst_node in snn_layer_to_nodes_mapping['snn1']:
                    trace_events.append(f"{step} {src_node} {dst_node} 1 input")

            # 2. Tráfico SNN1 -> SNN2
            spikes1 = (spk1 > 0).nonzero(as_tuple=False)
            for s in spikes1:
                channel_idx = s[1].item() % len(snn_layer_to_nodes_mapping['snn1'])
                src_node = snn_layer_to_nodes_mapping['snn1'][channel_idx]
                for dst_node in snn_layer_to_nodes_mapping['snn2']:
                    trace_events.append(f"{step} {src_node} {dst_node} 1 snn1")

            # 3. Tráfico SNN2 -> Output
            spikes2 = (spk2 > 0).nonzero(as_tuple=False)
            for s in spikes2:
                channel_idx = s[1].item() % len(snn_layer_to_nodes_mapping['snn2'])
                src_node = snn_layer_to_nodes_mapping['snn2'][channel_idx]
                for dst_node in snn_layer_to_nodes_mapping['output']:
                    trace_events.append(f"{step} {src_node} {dst_node} 1 snn2")

            if step % 10 == 0:
                print(f"Paso {step} completado. Eventos acumulados: {len(trace_events)}")

    with open(filename, 'w') as f:
        for event in trace_events:
            f.write(event + "\n")

    print(f"\n¡Éxito! Traza generada: {filename} con {len(trace_events)} eventos.")
    return trace_events

# --- EJECUCIÓN ---
print("Obteniendo muestra de datos...")
sample_data, sample_targets = next(iter(testloader))
# Aseguramos que sea (time, batch, channel, h, w)
single_stimulus = sample_data[0:1].float().to(device).transpose(0, 1) # Restaurar resolución original para evitar errores de kernel
print(f"Forma del estímulo: {single_stimulus.shape}")

generic_trace = generate_generic_trace(net, single_stimulus, snn_layer_to_nodes_mapping, connections)

"""## 8. Análisis Estadístico de la Red y la Carga"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# from google.colab import files

def analyze_trace_advanced(trace_events, num_nodes, filename="network_events_log.csv"):
    if not trace_events:
        print("No hay eventos en la traza para analizar.")
        return

    # 1. Crear DataFrame y exportar a CSV para descarga
    df = pd.DataFrame([event.split() for event in trace_events],
                      columns=['timestamp', 'source', 'destination', 'packet_size', 'packet_type'])
    df = df.astype({'timestamp': int, 'source': int, 'destination': int, 'packet_size': int})

    # Guardar y descargar el log
    df.to_csv(filename, index=False)
    print(f"--- Log de eventos generado: {filename} ---")
    # files.download(filename) # Esto disparará la descarga en tu navegador

    print("\n" + "="*50)
    print("   ANÁLISIS AVANZADO DE RED Y CUELLOS DE BOTELLA")
    print("="*50)

    # 2. Métricas de Carga y Congestión
    traffic_by_source = df.groupby('source')['packet_size'].sum()
    traffic_by_dest = df.groupby('destination')['packet_size'].sum()

    # Identificar Hotspots (Nodos con carga > 2 desviaciones estándar de la media)
    mean_load = traffic_by_source.mean()
    std_load = traffic_by_source.std()
    hotspots = traffic_by_source[traffic_by_source > (mean_load + std_load)].index.tolist()

    # 3. Visualizaciones Detalladas
    plt.figure(figsize=(20, 12))

    # A. Carga Temporal (Identificar picos de congestión)
    plt.subplot(2, 2, 1)
    temporal_load = df.groupby('timestamp')['packet_size'].sum()
    plt.plot(temporal_load.index, temporal_load.values, marker='o', color='firebrick')
    plt.fill_between(temporal_load.index, temporal_load.values, alpha=0.2, color='red')
    plt.title('Carga de Red por Ciclo de Tiempo (Picos de Congestión)')
    plt.xlabel('Timestamp (Ciclo)')
    plt.ylabel('Carga Total')

    # B. Distribución de Carga por Nodo (Balance de Carga)
    plt.subplot(2, 2, 2)
    node_load = pd.DataFrame({'Generada': traffic_by_source, 'Recibida': traffic_by_dest}).fillna(0)
    node_load.plot(kind='bar', ax=plt.gca())
    plt.title('Balance de Carga: Generada vs Recibida por Nodo')
    plt.xlabel('ID del Nodo')
    plt.ylabel('Carga (Bytes/Paquetes)')

    # C. Matriz de Tráfico (Heatmap de Cuellos de Botella)
    plt.subplot(2, 2, 3)
    traffic_matrix = pd.pivot_table(df, values='packet_size', index='source', columns='destination', aggfunc='sum', fill_value=0)
    sns.heatmap(traffic_matrix, annot=True, fmt="d", cmap="YlOrRd")
    plt.title('Mapa de Calor de Interconexión (Hotspots de Tráfico)')

    # D. Carga por Tipo de Capa (Contribución al Tráfico)
    plt.subplot(2, 2, 4)
    type_load = df.groupby('packet_type')['packet_size'].sum()
    plt.pie(type_load.values, labels=type_load.index, autopct='%1.1f%%', colors=sns.color_palette('pastel'))
    plt.title('Distribución de Carga por Capa SNN')

    plt.tight_layout()
     # plt.show())

    # 4. Informe de Diagnóstico
    print("\n--- DIAGNÓSTICO DE LA RED ---")
    print(f"Total de eventos registrados: {len(df)}")
    print(f"Nodo con mayor carga generada: {traffic_by_source.idxmax()} ({traffic_by_source.max()} unidades)")
    print(f"Nodo con mayor carga recibida: {traffic_by_dest.idxmax()} ({traffic_by_dest.max()} unidades)")

    if hotspots:
        print(f"⚠️ CUELLOS DE BOTELLA DETECTADOS en los nodos: {hotspots}")
        print("Sugerencia: Considera repartir las neuronas de estos nodos en procesadores vecinos.")
    else:
        print("✅ La carga parece estar bien balanceada entre los nodos.")

# Ejecutar el análisis
analyze_trace_advanced(generic_trace, num_nodes)